# Generated by Django 5.2 on 2025-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_doll_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awemecustomuser",
            name="provider_avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalawemecustomuser",
            name="provider_avatar_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
