# Generated by Django 5.2 on 2025-05-09 15:04

import ai_doll_backend.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_doll_backend", "0002_awemecustomuser_provider_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awemecustomuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalawemecustomuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AwemeUserCredits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits", models.IntegerField(default=0)),
                ("acc_credits", models.IntegerField(default=0)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_subscription", models.BooleanField(default=False)),
                ("plan_type", models.CharField(blank=True, max_length=255, null=True)),
                ("subscription_start_time", models.DateTimeField(null=True)),
                ("subscription_end_time", models.DateTimeField(null=True)),
                ("cancel_at_end_time", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.IntegerField(default=ai_doll_backend.models.get_timestamp),
                ),
                (
                    "updated_at",
                    models.IntegerField(default=ai_doll_backend.models.get_timestamp),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAwemeUserCredits",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("credits", models.IntegerField(default=0)),
                ("acc_credits", models.IntegerField(default=0)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_subscription", models.BooleanField(default=False)),
                ("plan_type", models.CharField(blank=True, max_length=255, null=True)),
                ("subscription_start_time", models.DateTimeField(null=True)),
                ("subscription_end_time", models.DateTimeField(null=True)),
                ("cancel_at_end_time", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.IntegerField(default=ai_doll_backend.models.get_timestamp),
                ),
                (
                    "updated_at",
                    models.IntegerField(default=ai_doll_backend.models.get_timestamp),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aweme user credits",
                "verbose_name_plural": "historical aweme user creditss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
